---
- hosts: mywebservers
  become: all

  tasks:
  - name: install tree on ubuntu server
    apt: 
        name: "{{mytreeserver}}"
        state: present

  - name: install git on ubuntu server
    apt: 
        name: "{{mygitserver}}"
        state: present 

  - name: install wget on ubuntu server
    apt: 
        name: "{{mywgetserver}}"
        state: present