---
- hosts: all
  become: yes

  tasks:
  - name: install apache2 on ubuntu server
    apt: 
        name: apache2
        state: persent

  - name: install git
    apt: 
        name: gitc
        state: present


  