---
- hosts: git_wget_tree
  become: yes
  tasks:
   
   - include_task: MyFile.yml

   - name: install git on ubuntu server
     apt: 
        name: "{{mygitserver}}"
        state: present
     


   - name: install wget on ubuntu server
     apt: 
        name: "{{mywgetserver}}"
        state: present
     

  
   - name: install tree on ubuntu server
     apt: 
        name: "{{mytreeserver}}"
        state: present
         
 

  