---
- hosts: all
  become: yes

  tasks:
  - name: install tree on ubuntu server
    apt: 
        name: "{{mytreeserver}}"
        state: present

  - name: i want to start ubuntu/tree server
    service: 
         name: "{{mytreeserver}}"     
         state: started




  - name: install git on ubuntu server
    apt: 
        name: "{{mygitserver}}"
        state: present 

  - name: i want to start ubuntu/git server
    service: 
         name: "{{mygitserver}}"     
         state: started



         

  - name: install wget on ubuntu server
    apt: 
        name: "{{mywgetserver}}"
        state: present

  - name: i want to start ubuntu/wget server
    service: 
         name: "{{mywgetserver}}"     
         state: started