---
- hosts: git_wget_tree
  become: yes
  tasks:

   - name: i want to create file on mode
     file:
        path: /home/ubuntu/myfirstfile
        state: touch
           
   - name: install git on ubuntu server
     apt: 
        name: "{{mygitserver}}"
        statee: present
     ignore_errors: true


   - name: install wget on ubuntu server
     apt: 
        name: "{{mywgetserver}}"
        state: present
     

  
   - name: install tree on ubuntu server
     apt: 
        name: "{{mytreeserver}}"
        state: present
         
 

  