---
- hosts: git_wget_tree
  become: yes
  tasks:

        
   - name: install git on ubuntu server
     apt: 
        name: "{{mygitserver}}"
        statee: present
     


   - name: install wget on ubuntu server
     apt: 
        name: "{{mywgetserver}}"
        state: present
     

  
   - name: install tree on ubuntu server
     apt: 
        name: "{{mytreeserver}}"
        state: present
         
 

  