---
- hosts: git_wget_tree
  become: yes

  tasks:

   - name: i want to execute any linux command
     command: hostname -f
     register: myfirsttaskresult

   - name: i want to display result which is in myfirsttaskresult
     debug: 
        msg: "{{myfirsttaskresult}}"  




        
        
   - name: install git on ubuntu server
     apt: 
        name: "{{mygitserver}}"
        state: present
     when: myfirsttaskresult.stderr != "" 


   - name: install wget on ubuntu server
     apt: 
        name: "{{mywgetserver}}"
        state: present
     when: myfirsttaskresult.stderr == ""    

  
   - name: install tree on ubuntu server
     apt: 
        name: "{{mytreeserver}}"
        state: present
     when: myfirsttaskresult.stderr == ""     
 

  