---
- hosts: mywebserver
  become: yes

  tasks:
  
  - name: i want to install webserver
    apt: 
        name: "{{mywebpackonubuntu}}"
        state: present
    when: ansible_os_family=="Debian"  
     


  - name: i want to start webserver
    service: 
        name: "{{mywebpackonubuntu}}"
        state: started
    when: ansible_os_family=="Debian"

  - name: i want to install java11 webserver
    apt:
        name: "{{myjdkonubuntu}}"
        state: latest
    
  
  - include_tasks: MyFile.yml

  - name: Copy MyTextFile from node side
    copy:
      src: MyTextFile
      dest: /home/ubuntu

  - name: Download files from internet
    get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20-fulldocs.tar.gz
        dest: /home/ubuntu/apache-tomcat-10.0.20-fulldocs.tar.gz
        force_basic_auth: yes

  - name: Copy dyno/dynamic file into node side
    template:
        src: Indexfile.j2
        dest: /var/www/html/index.html
    notify: restartwebserver

    handlers:
     - name: restartwebserver
       service: 
          name: "{{mywebpackonubuntu}}"
          state: restarted
       when: ansible_os_family=="Debian" 
    

  



  


 