---
- hosts: mywebserver
  become: yes

  tasks:
  - name: i want to install webserver
    apt: 
        name: "{{mywebpackonubuntu}}"
        state: present
    when: ansible_os_family=="Debian"   
     

  - name: i want to start webserver
    service: 
        name: "{{mywebpackonubuntu}}"
        state: started
    when: ansible_os_family=="Debian"

  - name: i want to install java11 webserver
    service:
        name: "{{myjdk11onubuntu}}"
        state: latest
    



  


 